version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: company
      MYSQL_DATABASE: company
      MYSQL_USER: company
      MYSQL_PASSWORD: company
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password # Add this line
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    container_name: backend_container
    depends_on:
      - db
    ports:
      - "3000:3000"
